name: CI — Test & Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest -q || true; else echo "No tests found"; fi

      - name: Upload test summary (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ./test-*.log || true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Run linters if present
        run: |
          if command -v flake8 >/dev/null 2>&1; then flake8 || true; else echo "flake8 not configured"; fi

# Notes:
# - This CI is intentionally ecosystem-agnostic. Add language-specific steps as required.
# - Keep permissions minimal; only `checks: write` is enabled to report status.
