name: Run pre-commit hooks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (needed by pre-commit)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

# Notes:
# - This workflow runs lint/formatting hooks in CI and will now fail if hooks return a non-zero status.
# - This enforces code quality checks in CI; if this is too strict initially, revert to a non-blocking mode.