name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write
  issues: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Notes:
# - Releases will be created for tags like v1.2.3. The current artifact path is `dist/**` — change this pattern if your project outputs builds/artifacts elsewhere.
# - Customize artifacts and signing as needed.
