---
name: "Reusable CI"

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
      run-tests:
        required: false
        type: boolean
        default: true
      run-lint:
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  checks: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ inputs.python-version != '' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        if: ${{ inputs.run-tests || inputs.run-lint }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        if: ${{ inputs.run-tests }}
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest -q; else echo "No tests found"; fi

      - name: Run linter
        if: ${{ inputs.run-lint }}
        run: |
          if command -v flake8 >/dev/null 2>&1; then flake8; else echo "flake8 not configured"; fi

# Use this reusable workflow from other workflows:
# jobs:
#   ci:
#     uses: ./.github/workflows/reusable-ci.yml
#     with:
#       python-version: '3.11'
#       run-tests: true
#       run-lint: true
