name: Secrets Check

on:
  workflow_dispatch:
    inputs:
      secret_names:
        description: 'Comma-separated list of secret names to check'
        required: false
        default: 'PGP_PRIVATE_KEY,GGSHIELD_API_KEY'
      fail_on_missing:
        description: 'Fail if any secret is missing (true/false)'
        required: false
        default: 'true'
  schedule:
    - cron: '0 3 * * *' # nightly at 03:00 UTC (daily)


permissions:
  contents: read
  issues: write


jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets via API
        uses: actions/github-script@v6
        with:
          script: |
            const input = core.getInput('secret_names') || '';
            const failOnMissing = (core.getInput('fail_on_missing') || 'true') === 'true';
            const required = input.split(',').map(s => s.trim()).filter(Boolean);
            core.info(`Checking secrets: ${required.join(', ')}`);
            const resp = await github.rest.actions.listRepoSecrets({ owner: context.repo.owner, repo: context.repo.repo });
            const present = resp.data.secrets.map(s => s.name);
            const missing = required.filter(r => !present.includes(r));
            if (missing.length > 0) {
              const msg = `Missing secrets: ${missing.join(', ')}`;

              // Create an issue if one does not already exist
              const title = `Missing required repository secrets: ${missing.join(', ')}`;
              const { data: issues } = await github.rest.issues.listForRepo({ owner: context.repo.owner, repo: context.repo.repo, state: 'open', per_page: 100 });
              const exists = issues.some(i => i.title === title);
              if (!exists) {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title,
                  body: `The following required repository secrets are missing:\n\n- ${missing.join('\n- ')}\n\nThis check runs nightly and can be run manually via the Actions tab.`,
                  labels: ['security']
                });
                core.info('Created issue for missing secrets.');
              } else {
                core.info('An open issue for missing secrets already exists.');
              }

              if (failOnMissing) core.setFailed(msg); else core.warning(msg);
            } else {
              core.info(`All secrets present: ${required.join(', ')}`);
            }

# Notes:
# - This workflow requires the runner to have `secrets: read` permission to list repo secrets.
# - Run this manually (workflow_dispatch) or wire it into a schedule if you want periodic checks.