name: Secret Scanning (Gitleaks)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 4 * * 0' # weekly on Sunday at 04:00 UTC

permissions:
  contents: read
  issues: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v1
        with:
          args: '--no-git -v'

      - name: Create issue for findings
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[SECRET SCAN] Potential secret detected by gitleaks"
          content-file: findings.txt

# Notes:
# - Gitleaks is a best-effort detector for secrets in the repo and history. Review any findings carefully.
# - For enterprise-grade scanning, consider GitHub Advanced Security Secret Scanning.
