---
name: Shell & PowerShell Lint

permissions:
  contents: read
  packages: write
  issues: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck (sh)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:

  psscriptanalyzer:
      name: PSScriptAnalyzer (PowerShell)
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Run PSScriptAnalyzer
          shell: pwsh
          run: |
            Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -AllowClobber
            # Run analyzer; do not fail the workflow to avoid blocking PRs on small style issues
            Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error -ExcludeRule 'PSAvoidUsingWriteHost' || true

# Notes:
# - Releases will be created for tags like v1.2.3. The current artifact path is `dist/**` — change this pattern if your project outputs builds/artifacts elsewhere.
# - Customize artifacts and signing as needed.